---
deployment:
  tasks:
    - export DEPLOYPATH=/home/d34fcetzlilchq/public_html/wp-content/plugins/DentSoftOnlineRandevu/
    - /bin/mkdir -p "$DEPLOYPATH"
    - >
      /usr/bin/rsync -a --delete
      --exclude='.git/'
      --exclude='.gitignore'
      --exclude='.cpanel.yml'
      --exclude='README.md'
      --exclude='backup/'
      /home/d34fcetzlilchq/git-deploy/CapaOrtodonti_Randevu/ "$DEPLOYPATH"
